#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import json
import math
import shutil
from pathlib import Path


STUDY_ROOT = Path(__file__).resolve().parents[1]
BASE_DIR = STUDY_ROOT / "base"
CASES_DIR = STUDY_ROOT / "cases"
STUDIES_DIR = CASES_DIR / "studies"
TEMPLATE_PATH = BASE_DIR / "in.condensation.template"
DEFAULT_CONFIG_NAME = "parameters.json"
ASSET_FILES = ("water.species", "water.vss")


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def dump_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as handle:
        json.dump(data, handle, indent=2, sort_keys=True)
        handle.write("\n")


def resolve_config_path(config_arg: Path | None) -> Path:
    if config_arg is not None:
        return config_arg.resolve()

    matches = sorted(STUDIES_DIR.glob(f"*/{DEFAULT_CONFIG_NAME}"))
    if len(matches) == 1:
        return matches[0].resolve()
    if not matches:
        raise FileNotFoundError(
            f"No default configuration found. Create cases/studies/<study_name>/{DEFAULT_CONFIG_NAME} "
            "or pass --config explicitly."
        )

    match_list = "\n".join(f"  - {path}" for path in matches)
    raise FileNotFoundError(
        "Multiple study parameter files were found. Pass --config explicitly.\n"
        f"{match_list}"
    )


def format_float(value: float) -> str:
    return f"{value:.12g}"


def slug_float(value: float) -> str:
    sign = "m" if value < 0.0 else ""
    text = f"{abs(value):.6g}"
    return sign + text.replace(".", "p")


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def contact_line_halfwidth(radius: float, theta_deg: float) -> float:
    return radius * math.sin(math.radians(theta_deg))


def circular_cap_arc_length(radius: float, theta_deg: float) -> float:
    return 2.0 * radius * math.radians(theta_deg)


def compute_grid_count(length: float, cell_size: float, axis_name: str) -> int:
    raw_count = length / cell_size
    rounded_count = round(raw_count)
    require(
        rounded_count > 0 and math.isclose(raw_count, rounded_count, rel_tol=0.0, abs_tol=1.0e-9),
        f"{axis_name} length {format_float(length)} is not an integer multiple of cell_size {format_float(cell_size)}.",
    )
    return int(rounded_count)


def build_case_name(geometry_mode: str, top_boundary_velocity: float, spacing: float | None) -> str:
    parts = [geometry_mode, f"vtop_{slug_float(top_boundary_velocity)}"]
    if spacing is not None:
        parts.insert(1, f"dx_{slug_float(spacing)}")
    return "_".join(parts)


def generate_half_arc_surface(path: Path, radius: float, theta_deg: float, surface_gap: float, segments: int) -> None:
    require(segments >= 2, "droplet_arc_segments must be at least 2.")
    theta = math.radians(theta_deg)
    center_y = surface_gap - radius * math.cos(theta)

    # Apex -> right contact point so that the 2D outward normal
    # (+z x (p2-p1)) points into the gas region.
    angles = [theta * (i / segments) for i in range(segments + 1)]
    points = [(radius * math.sin(angle), center_y + radius * math.cos(angle)) for angle in angles]

    with path.open("w", encoding="utf-8") as handle:
        handle.write("2D droplet circular-arc surface generated by generate_cases.py\n\n")
        handle.write(f"{len(points)} points\n")
        handle.write(f"{segments} lines\n\n")
        handle.write("Points\n\n")
        for index, (x_coord, y_coord) in enumerate(points, start=1):
            handle.write(f"{index} {format_float(x_coord)} {format_float(y_coord)}\n")
        handle.write("\nLines\n\n")
        for index in range(1, segments + 1):
            handle.write(f"{index} {index} {index + 1}\n")


def render_geometry_section(centers: list[float]) -> str:
    lines = [
        "# Explicit 2D droplet surfaces generated as circular arcs in each case directory.",
        "# Each droplet is kept in its own surface group for droplet-wise diagnostics.",
    ]
    for index, x_center in enumerate(centers, start=1):
        lines.extend(
            [
                f"read_surf           sdata.droplet group droplet_{index} &",
                f"                    trans {format_float(x_center)} 0.0 0.0",
            ]
        )
    return "\n".join(lines)


def render_surf_modify_section(droplet_count: int) -> str:
    return "\n".join(f"surf_modify         droplet_{index} collide droplet_sc" for index in range(1, droplet_count + 1))


def render_surface_emit_section(droplet_count: int) -> str:
    lines = [
        "# Vapor source at the droplet surface, following the evaporation-style pattern.",
        "# The emitted half-Maxwellian uses nrho_emit = coeff * vapor_number_density.",
    ]
    for index in range(1, droplet_count + 1):
        lines.append(f"fix                 droplet_emit_{index} emit/surf droplet_emit droplet_{index} normal yes")
    return "\n".join(lines)


def render_image_section(image_dump_every: int, defaults: dict, geometry: dict) -> str:
    if image_dump_every <= 0:
        return ""

    dx = (geometry["xhi"] - geometry["xlo"]) / geometry["grid_nx"]
    dy = (geometry["yhi"] - geometry["ylo"]) / geometry["grid_ny"]
    min_spacing = min(dx, dy)
    radius = defaults["radius"]
    particle_diameter = min(0.08 * min_spacing, 0.02 * radius)
    grid_line_diameter = 0.02 * min_spacing
    surf_line_diameter = 0.04 * min_spacing

    return "\n".join(
        [
            f"dump                img image all {image_dump_every} image.*.ppm type type pdiam {format_float(particle_diameter)} &",
            f"                    surf proc {format_float(surf_line_diameter)} size 512 512 zoom 1.6 gline yes {format_float(grid_line_diameter)}",
            "dump_modify         img pad 4",
        ]
    )


def render_centerline_section(defaults: dict, geometry: dict) -> str:
    dump_every = defaults["sampling_steps"]
    dx = (geometry["xhi"] - geometry["xlo"]) / geometry["grid_nx"]
    band_cells = defaults["centerline_band_cells"]
    half_thickness = 0.500001 * band_cells * dx
    line_xlo = geometry["xlo"]
    line_xhi = min(geometry["xhi"], geometry["xlo"] + band_cells * dx + half_thickness)

    return "\n".join(
        [
            "# Time-averaged centerline fields in a thin band around x = 0.",
            "# f_centerline_avg columns are: nrho u v temp press.",
            f"region              xline block {format_float(line_xlo)} {format_float(line_xhi)} INF INF INF INF",
            "group               centerline grid region xline center",
            "compute             centerline_flow grid centerline water nrho u v",
            "compute             centerline_thermo thermal/grid centerline water temp press",
            f"fix                 centerline_avg ave/grid centerline 1 {dump_every} {dump_every} &",
            "                    c_centerline_flow[*] c_centerline_thermo[*] ave one",
            f"dump                centerline_dump grid centerline {dump_every} line_x0.dump id xc yc f_centerline_avg[*]",
        ]
    )


def render_full_grid_section(defaults: dict) -> str:
    dump_every = defaults["sampling_steps"]
    return "\n".join(
        [
            "# Time-averaged whole-domain grid fields for steady-state inspection.",
            "# f_grid_avg columns are: nrho u v temp press.",
            "compute             grid_flow grid all water nrho u v",
            "compute             grid_thermo thermal/grid all water temp press",
            f"fix                 grid_avg ave/grid all 1 {dump_every} {dump_every} &",
            "                    c_grid_flow[*] c_grid_thermo[*] ave one",
            f"dump                grid_dump grid all {dump_every} grid_steady.dump id xc yc f_grid_avg[*]",
        ]
    )


def render_diagnostics_section(droplet_count: int, production_run_steps: int, image_dump_every: int, defaults: dict, geometry: dict) -> str:
    sample_every = defaults["sampling_steps"]
    lines = [
        "# Per-droplet condensation diagnostics.",
        "# c_mflux_flux_* stores area-normalized mass flux per unit out-of-plane depth.",
        "# c_mflux_flow_* stores line-integrated mass flow per unit depth.",
    ]
    for index in range(1, droplet_count + 1):
        lines.extend(
            [
                f"compute             mflux_flux_{index} surf droplet_{index} water mflux",
                f"compute             mflux_flow_{index} surf droplet_{index} water mflux norm flow",
                f"fix                 avg_droplet_{index} ave/surf droplet_{index} 1 {sample_every} {sample_every} &",
                f"                    c_mflux_flux_{index}[1] c_mflux_flow_{index}[1] ave one",
                f"dump                surf_droplet_{index} surf droplet_{index} {sample_every} surf_droplet{index}.dump id area f_avg_droplet_{index}[1] f_avg_droplet_{index}[2]",
                f"dump                surf_geom_{index} surf droplet_{index} {production_run_steps} surf_geom_droplet{index}.dump id area v1x v1y v2x v2y",
                "",
            ]
        )

    lines.extend([render_centerline_section(defaults, geometry), "", render_full_grid_section(defaults), ""])
    image_section = render_image_section(image_dump_every, defaults, geometry)
    if image_section:
        lines.extend([image_section, ""])
    return "\n".join(lines).rstrip()


def render_pre_run_section(defaults: dict) -> str:
    start_sampling_step = defaults["start_sampling_step"]
    if start_sampling_step <= 0:
        return ""
    return f"# Equilibration run before any steady-state averaging begins.\nrun                 {start_sampling_step}"


def render_paraview_grid_description(geometry: dict) -> str:
    return "\n".join(
        [
            "# Case-local grid description for tools/paraview/grid2paraview.py",
            "dimension           2",
            f"create_box          {format_float(geometry['xlo'])} {format_float(geometry['xhi'])} {format_float(geometry['ylo'])} {format_float(geometry['yhi'])} {format_float(geometry['zlo'])} {format_float(geometry['zhi'])}",
            f"create_grid         {geometry['grid_nx']} {geometry['grid_ny']} 1",
        ]
    )


def render_run_single_script() -> str:
    return "\n".join(
        [
            "#!/bin/bash",
            "#SBATCH --nodes 1",
            "#SBATCH --job-name condensation2d",
            "#SBATCH --ntasks-per-node 32",
            "#SBATCH --cpus-per-task 1",
            "#SBATCH --time 7-00:00:00",
            "",
            "set -euo pipefail",
            "",
            'case_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
            'study_root="$(cd "$case_dir/../../.." && pwd)"',
            "",
            'module purge',
            'module load gcc',
            'module load openmpi',
            "",
            'if [[ -n "${SPARTA_BIN:-}" ]]; then',
            '  sparta_bin="$SPARTA_BIN"',
            'elif [[ -x "$case_dir/spa_mpi" ]]; then',
            '  sparta_bin="$case_dir/spa_mpi"',
            'elif [[ -x "$study_root/spa_mpi" ]]; then',
            '  sparta_bin="$study_root/spa_mpi"',
            'else',
            '  echo "Could not find spa_mpi. Set SPARTA_BIN, place spa_mpi in the case directory, or place one shared spa_mpi at $study_root/spa_mpi." >&2',
            '  exit 1',
            'fi',
            "",
            'cd "$case_dir"',
            'srun "$sparta_bin" < in.condensation > log.txt',
        ]
    )


def render_study_run_script() -> str:
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "",
            "set -euo pipefail",
            "",
            'study_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
            'case_list="$study_dir/case_list.txt"',
            "",
            'if [[ ! -f "$case_list" ]]; then',
            '  echo "Case list not found: $case_list" >&2',
            "  exit 1",
            "fi",
            "",
            'while IFS= read -r case_relpath; do',
            '  [[ -z "$case_relpath" ]] && continue',
            '  case_dir="$study_dir/$(basename "$case_relpath")"',
            '  run_script="$case_dir/run_single.sh"',
            '  if [[ ! -x "$run_script" ]]; then',
            '    echo "Missing run script: $run_script" >&2',
            "    exit 1",
            "  fi",
            '  echo "Submitting $run_script"',
            '  (cd "$case_dir" && sbatch ./run_single.sh)',
            'done < "$case_list"',
        ]
    )


def build_geometry(case: dict) -> dict:
    defaults = case["defaults"]
    geometry_mode = case["geometry_mode"]
    spacing = case.get("spacing")
    radius = defaults["radius"]
    theta_deg = defaults["contact_angle_deg"]
    footprint_halfwidth = contact_line_halfwidth(radius, theta_deg)
    cap_height = radius * (1.0 - math.cos(math.radians(theta_deg)))
    box_length_x = defaults["box_length_x"]
    box_height = defaults["box_height"]
    cell_size = defaults["cell_size"]

    require(cap_height < box_height, "Droplet cap height exceeds the box height.")

    if geometry_mode == "single_open_half":
        xlo = 0.0
        xhi = 0.5 * box_length_x
        centers = [0.0]
        boundary_x = "ro"
        symmetry_multiplier = 2
    elif geometry_mode == "array_half":
        require(spacing is not None, "array_half cases require a droplet spacing.")
        require(spacing > 2.0 * footprint_halfwidth, "Droplet spacing must exceed twice the contact-line half-width.")
        xlo = 0.0
        xhi = 0.5 * spacing
        centers = [0.0]
        boundary_x = "rr"
        symmetry_multiplier = 2
    else:
        raise ValueError(f"Unsupported geometry mode: {geometry_mode}")

    require(footprint_halfwidth <= xhi + 1.0e-12, "Droplet footprint extends past xhi.")

    grid_nx = compute_grid_count(xhi - xlo, cell_size, "x")
    grid_ny = compute_grid_count(box_height, cell_size, "y")

    return {
        "xlo": xlo,
        "xhi": xhi,
        "ylo": 0.0,
        "yhi": box_height,
        "zlo": -0.5 * cell_size,
        "zhi": 0.5 * cell_size,
        "centers": centers,
        "boundary_x": boundary_x,
        "boundary_y": "ss",
        "boundary_z": "pp",
        "droplet_count": len(centers),
        "footprint_halfwidth": footprint_halfwidth,
        "cap_height": cap_height,
        "symmetry_multiplier": symmetry_multiplier,
        "cell_size": cell_size,
        "grid_nx": grid_nx,
        "grid_ny": grid_ny,
    }


def render_case_input(template_text: str, case: dict, geometry: dict) -> str:
    defaults = case["defaults"]
    production_run_steps = defaults["run_steps"] - defaults["start_sampling_step"]
    placeholders = {
        "__SEED__": str(defaults["seed"]),
        "__GRIDCUT__": format_float(defaults["gridcut"]),
        "__BOUNDARY_X__": geometry["boundary_x"],
        "__BOUNDARY_Y__": geometry["boundary_y"],
        "__BOUNDARY_Z__": geometry["boundary_z"],
        "__XLO__": format_float(geometry["xlo"]),
        "__XHI__": format_float(geometry["xhi"]),
        "__YLO__": format_float(geometry["ylo"]),
        "__YHI__": format_float(geometry["yhi"]),
        "__ZLO__": format_float(geometry["zlo"]),
        "__ZHI__": format_float(geometry["zhi"]),
        "__TWALL__": format_float(defaults["temperature_k"]),
        "__COEFF__": format_float(defaults["condensation_coefficient"]),
        "__TOP_VY__": format_float(case["top_boundary_velocity"]),
        "__GRID_NX__": str(geometry["grid_nx"]),
        "__GRID_NY__": str(geometry["grid_ny"]),
        "__VAPOR_NRHO__": format_float(defaults["vapor_number_density"]),
        "__FNUM__": format_float(defaults["fnum"]),
        "__GEOMETRY_SECTION__": render_geometry_section(geometry["centers"]),
        "__SURF_MODIFY_SECTION__": render_surf_modify_section(geometry["droplet_count"]),
        "__SURFACE_EMIT_SECTION__": render_surface_emit_section(geometry["droplet_count"]),
        "__TIMESTEP__": format_float(defaults["time_step"]),
        "__PRE_RUN_SECTION__": render_pre_run_section(defaults),
        "__DIAGNOSTICS_SECTION__": render_diagnostics_section(
            geometry["droplet_count"],
            production_run_steps,
            defaults["image_dump_every"],
            defaults,
            geometry,
        ),
        "__STATS_EVERY__": str(defaults["stats_every"]),
        "__PRODUCTION_RUN_STEPS__": str(production_run_steps),
    }

    rendered = template_text
    for key, value in placeholders.items():
        rendered = rendered.replace(key, value)
    return rendered


def build_case_metadata(case_name: str, case: dict, geometry: dict) -> dict:
    defaults = case["defaults"]
    full_arc_length = circular_cap_arc_length(defaults["radius"], defaults["contact_angle_deg"])
    droplets = []
    for index, x_center in enumerate(geometry["centers"], start=1):
        droplets.append(
            {
                "name": f"droplet_{index}",
                "center_x": x_center,
                "symmetry_multiplier": geometry["symmetry_multiplier"],
                "analytic_arc_length_full_m": full_arc_length,
                "analytic_contact_halfwidth_m": geometry["footprint_halfwidth"],
            }
        )

    return {
        "case_name": case_name,
        "study_name": case["study_name"],
        "geometry_mode": case["geometry_mode"],
        "spacing": case.get("spacing"),
        "top_boundary_velocity": case["top_boundary_velocity"],
        "temperature_k": defaults["temperature_k"],
        "radius": defaults["radius"],
        "contact_angle_deg": defaults["contact_angle_deg"],
        "surface_gap": defaults["surface_gap"],
        "condensation_coefficient": defaults["condensation_coefficient"],
        "time_step": defaults["time_step"],
        "run_steps": defaults["run_steps"],
        "start_sampling_step": defaults["start_sampling_step"],
        "sampling_steps": defaults["sampling_steps"],
        "stats_every": defaults["stats_every"],
        "cell_size": geometry["cell_size"],
        "box_length_x": defaults["box_length_x"],
        "box_height": defaults["box_height"],
        "grid_cells": [geometry["grid_nx"], geometry["grid_ny"], 1],
        "droplet_count": geometry["droplet_count"],
        "latent_heat_j_per_kg": defaults["latent_heat_j_per_kg"],
        "droplet_cap_height": geometry["cap_height"],
        "droplet_contact_halfwidth": geometry["footprint_halfwidth"],
        "simulation_bounds": {
            "xlo": geometry["xlo"],
            "xhi": geometry["xhi"],
            "ylo": geometry["ylo"],
            "yhi": geometry["yhi"],
            "zlo": geometry["zlo"],
            "zhi": geometry["zhi"],
        },
        "boundary_x": geometry["boundary_x"],
        "boundary_y": geometry["boundary_y"],
        "boundary_z": geometry["boundary_z"],
        "droplets": droplets,
    }


def iter_cases(config: dict) -> list[dict]:
    defaults = config["defaults"]
    sweep = config["sweep"]
    cases_cfg = config["cases"]
    velocities = sweep["top_boundary_velocity"]
    spacings = sweep["spacing"]
    study_name = config["study_name"]

    require(defaults["start_sampling_step"] >= 0, "start_sampling_step must be non-negative.")
    require(defaults["sampling_steps"] > 0, "sampling_steps must be positive.")
    require(defaults["run_steps"] > defaults["start_sampling_step"], "run_steps must exceed start_sampling_step.")
    require((defaults["run_steps"] - defaults["start_sampling_step"]) % defaults["sampling_steps"] == 0,
            "run_steps - start_sampling_step must be divisible by sampling_steps.")

    rows = []
    if cases_cfg.get("include_single_reference", True):
        single_velocities = velocities if cases_cfg.get("single_reference_per_velocity", True) else [velocities[0]]
        for velocity in single_velocities:
            rows.append(
                {
                    "study_name": study_name,
                    "geometry_mode": cases_cfg["single_geometry_mode"],
                    "top_boundary_velocity": velocity,
                    "spacing": None,
                    "defaults": defaults,
                }
            )

    for velocity in velocities:
        for spacing in spacings:
            rows.append(
                {
                    "study_name": study_name,
                    "geometry_mode": cases_cfg["multi_geometry_mode"],
                    "top_boundary_velocity": velocity,
                    "spacing": spacing,
                    "defaults": defaults,
                }
            )
    return rows


def write_manifest(study_dir: Path, rows: list[dict]) -> None:
    fieldnames = ["case_name", "case_relpath", "geometry_mode", "top_boundary_velocity", "spacing", "droplet_count"]
    manifest_path = study_dir / "case_manifest.csv"
    with manifest_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    case_list_path = study_dir / "case_list.txt"
    with case_list_path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(f"{row['case_relpath']}\n")


def generate_cases(config_path: Path, force: bool) -> list[dict]:
    config = load_json(config_path)
    template_text = TEMPLATE_PATH.read_text(encoding="utf-8")
    study_name = config["study_name"]
    study_dir = STUDIES_DIR / study_name
    study_dir.mkdir(parents=True, exist_ok=True)
    manifest_rows = []

    for case in iter_cases(config):
        geometry = build_geometry(case)
        case_name = build_case_name(case["geometry_mode"], case["top_boundary_velocity"], case["spacing"])
        case_dir = study_dir / case_name
        if case_dir.exists():
            if not force:
                raise FileExistsError(f"{case_dir} already exists. Re-run with --force to replace it.")
            shutil.rmtree(case_dir)
        case_dir.mkdir(parents=True, exist_ok=True)

        rendered_input = render_case_input(template_text, case, geometry)
        (case_dir / "in.condensation").write_text(rendered_input + "\n", encoding="utf-8")
        (case_dir / "pv_grid.txt").write_text(render_paraview_grid_description(geometry) + "\n", encoding="utf-8")
        run_single_path = case_dir / "run_single.sh"
        run_single_path.write_text(render_run_single_script() + "\n", encoding="utf-8")
        run_single_path.chmod(0o755)
        generate_half_arc_surface(
            case_dir / "sdata.droplet",
            case["defaults"]["radius"],
            case["defaults"]["contact_angle_deg"],
            case["defaults"]["surface_gap"],
            case["defaults"]["droplet_arc_segments"],
        )

        metadata = build_case_metadata(case_name, case, geometry)
        dump_json(case_dir / "metadata.json", metadata)

        for asset_name in ASSET_FILES:
            shutil.copy2(BASE_DIR / asset_name, case_dir / asset_name)

        manifest_rows.append(
            {
                "case_name": case_name,
                "case_relpath": f"cases/studies/{study_name}/{case_name}",
                "geometry_mode": case["geometry_mode"],
                "top_boundary_velocity": case["top_boundary_velocity"],
                "spacing": "" if case["spacing"] is None else case["spacing"],
                "droplet_count": geometry["droplet_count"],
            }
        )

    write_manifest(study_dir, manifest_rows)
    run_script_path = study_dir / "run.sh"
    run_script_path.write_text(render_study_run_script() + "\n", encoding="utf-8")
    run_script_path.chmod(0o755)
    return manifest_rows


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate parametric SPARTA condensation2d cases.")
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help=f"Path to the JSON sweep configuration. Defaults to the only cases/studies/*/{DEFAULT_CONFIG_NAME} file if present.",
    )
    parser.add_argument("--force", action="store_true", help="Replace existing generated case directories.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    config_path = resolve_config_path(args.config)
    config = load_json(config_path)
    study_dir = STUDIES_DIR / config["study_name"]
    rows = generate_cases(config_path, args.force)
    print(f"Generated {len(rows)} case directories under {study_dir}")
    print(f"Parameters: {config_path}")
    print(f"Study manifest: {study_dir / 'case_manifest.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
